---
- hosts: linux
  become: yes
  become_method: sudo

  vars_files:
  - vars/linuxsecrets.yml

  tasks:
  - name: Ensure the Apache daemon is installed on Red Hat based distros
    dnf:
      name: httpd
      state: present
    when: ansible_os_family == 'RedHat'

  - name: Ensure that the Apache daemon is running on Red Hat based distros
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == 'RedHat'
  
  - name: Ensure the Apache daemon is installed on Debian based distros
    apt:
      name: apache2
      state: present
    when: ansible_os_family == 'Debian'

  - name: Ensure that the Apache daemon is running on Debian based distros
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'
